changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 🧪 Testing
      labels:
        - tests
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - refactor
    - title: ⚠️ Breaking Changes
      labels:
        - breaking
